#!/usr/bin/env python3
"""Emit a Markdown deliberation worksheet (stdlib only)."""

from __future__ import annotations

import argparse
from datetime import date


def build_sheet(title: str) -> str:
    today = date.today().isoformat()
    return f"""# Deliberation sheet: {title}

**Date:** {today}

## 1. Decision question (one sentence)


## 2. Counselors by role

| Role | Person / proxy | Notes |
|------|----------------|-------|
| Operator | | |
| Skeptic | | |
| Stakeholder / user | | |

## 3. Round A — strongest case *for* the leading option

| Counselor | Case FOR |
|-----------|----------|
| | |
| | |
| | |

## 4. Round B — strongest case *against* (concrete scenarios)

| Counselor | Case AGAINST |
|-----------|----------------|
| | |
| | |
| | |

## 5. Wound check (faithful wounds)

- Who loses if we are wrong?
- What uncomfortable fact are we avoiding?
- What would a faithful enemy say?

## 6. Decision record

**Decision:**


**Counsel summary (one line per role):**


**Named risk accepted:**


**Dissent (verbatim — best argument against the chosen path):**


---
_Generated by `deliberation_sheet.py`._
"""


def main() -> None:
    p = argparse.ArgumentParser(description="Print a Markdown deliberation worksheet to stdout.")
    p.add_argument("--title", required=True, help="Short title for the decision")
    args = p.parse_args()
    print(build_sheet(args.title.strip()))


if __name__ == "__main__":
    main()
