#!/usr/bin/env python3
"""Emit a Markdown template for prophetic-style systems diagnosis (stdlib only)."""

from __future__ import annotations

import argparse
from datetime import date


def build_template(system: str) -> str:
    today = date.today().isoformat()
    return f"""# Prophetic systems diagnosis: {system}

**Date:** {today}

## 1. Surface symptom (observable)


## 2. Organizational liturgy (what we never cancel / always fund)


## 3. Functional idol

*"This system cannot afford to disappoint:* **\_\_\_** *."*


## 4. Thin groups (who bears the cost)


## 5. Ignored warnings (two earlier signals rationalized away)

1.
2.

## 6. Concrete return (testable within ~one month)

| From | To |
|------|-----|
| | |
| | |
| | |

## 7. Shalom / relationship note (optional)

What relationship is traded away for the idol?


---
_Generated by `root_pattern_template.py`._
"""


def main() -> None:
    p = argparse.ArgumentParser(
        description="Print a Markdown prophetic diagnosis template to stdout.",
    )
    p.add_argument("--system", required=True, help="System, product, or incident name")
    args = p.parse_args()
    print(build_template(args.system.strip()))


if __name__ == "__main__":
    main()
