#!/usr/bin/env python3
"""Emit a Markdown xenia (reciprocal hospitality) audit worksheet (stdlib only)."""

from __future__ import annotations

import argparse
from datetime import date


def build_sheet(table_name: str) -> str:
    today = date.today().isoformat()
    return f"""# Xenia audit: {table_name}

**Date:** {today}

## 1. Roles for this phase

**Host** (offers space, access, time, cover):


**Guest** (receives; name concrete parties):


## 2. Minimum host obligations

What the host credibly owes in this context (not everything—minimum viable hospitality):

1. …
2. …
3. …

## 3. Minimum guest obligations

What the guest credibly owes (restraint, signal, thanks-as-action):

1. …
2. …
3. …

## 4. Reciprocity check

| Flow | Direction | Fair in the last 30/90 days? | Evidence |
|------|------------|-------------------------------|----------|
| Time / attention | | | |
| Risk / cover | | | |
| Reputation / credit | | | |

## 5. Abuse patterns (name honestly)

| Violation | Odyssey echo | Here it looks like | Response |
|-----------|----------------|-------------------|----------|
| | Suitors / etc. | | |
| | | | |

## 6. Repair or exit

If reciprocity cannot be restored:

- **Repair attempt** (one concrete change, owner, date):
- **Exit criteria** if repair fails:
- **Exit action** (reduce scope, end partnership, fork, rotate host):

---
_Generated by `xenia_audit.py`._
"""


def main() -> None:
    p = argparse.ArgumentParser(description="Print a Markdown xenia audit worksheet to stdout.")
    p.add_argument("--table", required=True, help="Name of the partnership, system, or table")
    args = p.parse_args()
    print(build_sheet(args.table.strip()))


if __name__ == "__main__":
    main()
