#!/usr/bin/env python3
"""Emit a Markdown nostos (wayfinding) worksheet (stdlib only)."""

from __future__ import annotations

import argparse
from datetime import date


def build_sheet(goal: str) -> str:
    today = date.today().isoformat()
    return f"""# Nostos sheet: {goal}

**Date:** {today}

## 1. Ithaca — what "home" means when this is done

Write one paragraph: who is safe, what is restored, what obligation is discharged.


## 2. Trials — external and internal

| Kind | Obstacle | What it costs if ignored |
|------|----------|-------------------------|
| External | | |
| External | | |
| Internal | | |
| Internal | | |

## 3. Derailment patterns

| Pattern | What here maps to it? | Early warning sign |
|---------|----------------------|-------------------|
| Lotus (forgetting the goal) | | |
| Siren (seductive "wisdom") | | |
| Underworld (unexamined past) | | |
| Scylla/Charybdis (forced tradeoff) | | |

## 4. Nostos checks (observable)

Three checks that mean we have **returned**, not merely stayed busy:

1. …
2. …
3. …

## 5. Review cadence

**Next review date:** YYYY-MM-DD

**Only question:** Are we closer to Ithaca, or only busier?

- Closer because:
- Busier because:
- What we prune next:

---
_Generated by `nostos_sheet.py`._
"""


def main() -> None:
    p = argparse.ArgumentParser(description="Print a Markdown nostos worksheet to stdout.")
    p.add_argument("--goal", required=True, help='Short name for the "north star" outcome')
    args = p.parse_args()
    print(build_sheet(args.goal.strip()))


if __name__ == "__main__":
    main()
