#!/usr/bin/env python3
"""Emit a Markdown phased proof / reveal worksheet (stdlib only)."""

from __future__ import annotations

import argparse
from datetime import date


def build_sheet(context: str) -> str:
    today = date.today().isoformat()
    return f"""# Phased proof: {context}

**Date:** {today}

## 1. What stays latent (one sentence)

What identity, capability, or intent remains veiled, and why?


## 2. Observer map

| Party | What they believe now | What they must not know yet | Risk if they learn too early |
|-------|------------------------|------------------------------|------------------------------|
| | | | |
| | | | |
| | | | |

## 3. Proofs (order matters — cheap to costly)

| Stage | Proof / test | Pass signal | Fail signal |
|-------|----------------|-------------|-------------|
| 1 | | | |
| 2 | | | |
| 3 | | | |

## 4. Reveal rule

**We reveal ___ only after ___ is true.**


## 5. Harm check

- Who bears risk while truth is delayed?
- What consent is implied, and is it fair?
- Kill switch: we abandon disguise if:


---
_Generated by `phase_reveal.py`._
"""


def main() -> None:
    p = argparse.ArgumentParser(description="Print a Markdown phased proof worksheet to stdout.")
    p.add_argument("--context", required=True, help="Short label for the situation")
    args = p.parse_args()
    print(build_sheet(args.context.strip()))


if __name__ == "__main__":
    main()
